language: generic
env:
  global:
    - CLI_VERSION=latest
before_install:
  - wget http://downloads.arduino.cc/arduino-cli/arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - tar xf arduino-cli-$CLI_VERSION-linux64.tar.bz2
  - mv arduino-cli-*-linux64 $HOME/bin/arduino-cli
  - mkdir -p $HOME/bin
  - arduino-cli config init
  - mv $PWD/travis/.cli-config.yml $HOME/.arduino15/arduino-cli.yaml
  - arduino-cli config dump
  - export PATH=$PATH:$HOME/bin
  - arduino-cli core update-index
  - arduino-cli config dump
  - arduino-cli core install arduino:avr
  - arduino-cli core install esp32:esp32
  - arduino-cli core install esp8266:esp8266
  - arduino-cli lib install ArduinoJson@5.13.4
  - arduino-cli lib install ArduinoWebsockets
  - buildExampleSketchEsp8266() { arduino-cli compile --warnings all --fqbn esp8266:esp8266:generic $PWD/examples/$1; }
  - buildExampleSketchEsp32() { arduino-cli compile --warnings all --fqbn esp32:esp32:esp32 $PWD/examples/$1; }
  - buildExampleSketch() { buildExampleSketchEsp8266 $1; buildExampleSketchEsp32 $1;}
install:
  - mkdir -p $HOME/Arduino/libraries
  - ln -s $PWD $HOME/Arduino/libraries/.
script:
  - buildExampleSketch "1.Objects/Get"
  - buildExampleSketch "1.Objects/Put"
  - buildExampleSketch "2.Collections/Add"
  - buildExampleSketch "2.Collections/Pop"
  - buildExampleSketch "3.Atomics/Datetime"
  - buildExampleSketch "3.Atomics/DecrementIncrement"
  - buildExampleSketch "3.Atomics/PutMinMax"
  - buildExampleSketch "4.Aggregation/Aggregations"
  - buildExampleSketch "Use-Cases/Increment"
  - buildExampleSketch "Use-Cases/Logger"
  - buildExampleSketch "Real-Time-Updates"
