proxy_type: auto
sketchbook_path: /home/travis/Arduino
arduino_data: /home/travis/.arduino15
board_manager: null
board_manager:
  additional_urls:
    - http://arduino.esp8266.com/stable/package_esp8266com_index.json
    - https://dl.espressif.com/dl/package_esp32_index.json